// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SettingAutocompleteController from "./setting_autocomplete_controller.js"
application.register("setting_autocomplete", SettingAutocompleteController)

import LocalAuthorityAutocompleteController from "./local_authority_autocomplete_controller.js"
application.register("local_authority_autocomplete", LocalAuthorityAutocompleteController)