---
version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 5
    versioning-strategy: auto
    labels:
      - dependencies
      - ruby

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 5
    versioning-strategy: auto
    labels:
      - dependencies
      - frontend
