---
inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.4.5

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: either
