---
services:
  app:
    container_name: recovery_test
    build:
      target: test
    image: recovery:test
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=postgres://postgres:password@db:5432/early_years_foundation_recovery_test
      - TRAINING_MODULES=demo-modules
      - TRACKING_ID=GTM-W6W95FD
    tty: true
    stdin_open: true

  db:
    volumes:
      - db_test:/var/lib/postgresql/data

volumes:
  db_test:
