---
services:
  app:
    container_name: recovery_test
    build:
      target: test
    image: recovery:test
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/early_years_foundation_recovery_test
      - RAILS_ENV=test
      - DOMAIN=recovery.app
      # - CONTENTFUL_ENVIRONMENT=test

      # revert before commit
      - CONTENTFUL_ENVIRONMENT=demo-copy
      - CONTENTFUL_PREVIEW=true

      - CONTENTFUL_MANAGEMENT_TOKEN=
      - BOT_TOKEN=bot_token
      - TIMEOUT_MINUTES=25
    tty: true
    stdin_open: true
