---
services:
  app:
    container_name: recovery_test
    build:
      target: test
    image: recovery:test
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/early_years_foundation_recovery_test
      - RAILS_ENV=test
      - DOMAIN=recovery.app
      - CONTENTFUL_ENVIRONMENT=test
      - CONTENTFUL_MANAGEMENT_TOKEN=
      - DEBUG=false
      - BOT_TOKEN=bot_token
      - TIMEOUT_MINUTES=25
      - GOV_ONE_BASE_URI=https://oidc.test.account.gov.uk
      - GOV_ONE_REDIRECT_URI=http://recovery.app/users/auth/openid_connect/callback
      - GOV_ONE_LOGOUT_REDIRECT_URI=http://recovery.app/users/sign_out
    tty: true
    stdin_open: true
