---
services:
  app:
    container_name: recovery_test
    build:
      target: test
    image: recovery:test
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/early_years_foundation_recovery_test
      - RAILS_ENV=test
      - DOMAIN=recovery.app
      - TRAINING_MODULES=demo-modules
      - BOT=bot_token
    tty: true
    stdin_open: true

  db:
    volumes:
      - db_test:/var/lib/postgresql/data

volumes:
  db_test:
