---
# ------------------------------------------------------------------------------
# Terraform workspaces align to Cloud Foundry spaces
defaults: &defaults
  RAILS_SERVE_STATIC_FILES: true
  RAILS_LOG_TO_STDOUT: true
  RAILS_MAX_THREADS: 5
  WEB_CONCURRENCY: 2
  RAILS_ENV: production
  NODE_ENV: production
  DATABASE_URL: postgres://postgres@localhost:5432/db
  FEEDBACK_URL: https://forms.office.com/Pages/ResponsePage.aspx?id=yXfS-grGoU2187O4s0qC-Qjm3BfYzDVIhkQadsLBtTxUMk01Qlc1R0dKRUQ0WEpPUUFYVzdWRllXUCQlQCN0PWcu
  GOVUK_APP_DOMAIN: london.cloudapps.digital
  GROVER_NO_SANDBOX: true
  EDITOR: vi

# ey-recovery
production:
  <<: *defaults
  DOMAIN: child-development-training.education.gov.uk
  WEB_CONCURRENCY: 8
  GOVUK_WEBSITE_ROOT: child-development-training
  TRACKING_ID: GTM-NFZ88TP  # Live data
  HOTJAR_SITE_ID: 3169682
  GOOGLE_CLOUD_BUCKET: eyfs-data-dashboard-live

# ey-recovery-staging
staging:
  <<: *defaults
  WEB_CONCURRENCY: 4
  DOMAIN: ey-recovery-staging.london.cloudapps.digital
  GOVUK_WEBSITE_ROOT: ey-recovery-staging
  TRACKING_ID: GTM-W6W95FD  # Test data
  GOOGLE_CLOUD_BUCKET: eyfs-data-dashboard-staging
  DASHBOARD_UPDATE: true # Daily at noon
  CONTENTFUL: true
  CONTENTFUL_ENVIRONMENT: genuine-with-5 # Defaults to "master" without override

# ey-recovery-dev
development:
  <<: *defaults
  DOMAIN: ey-recovery-dev.london.cloudapps.digital
  GOVUK_WEBSITE_ROOT: ey-recovery-dev
  TRAINING_MODULES: demo-modules
  GOOGLE_CLOUD_BUCKET: eyfs-data-dashboard-development
  DASHBOARD_UPDATE: true
  DASHBOARD_UPDATE_INTERVAL: '*/5 * * * *' # Every 5 mins
  CONTENTFUL: true
  CONTENTFUL_ENVIRONMENT: genuine-with-5 # Override would be "test/demo" normally

# ey-recovery-content
content:
  <<: *defaults
  # CONTENTFUL: true
  # CONTENTFUL_ENVIRONMENT: genuine-with-5
  # TRAINING_MODULES: demo-modules
  # @see .github/workflows/content.yml
  # DOMAIN: xxx.london.cloudapps.digital
  # GOVUK_WEBSITE_ROOT: xxx
