---
# ------------------------------------------------------------------------------
# Terraform workspaces align to Cloud Foundry spaces
defaults: &defaults
  RAILS_SERVE_STATIC_FILES: true
  RAILS_LOG_TO_STDOUT: true
  RAILS_MAX_THREADS: 5
  WEB_CONCURRENCY: 2 # NB: values greater than 2 impact caching
  RAILS_ENV: production
  NODE_ENV: production
  DATABASE_URL: postgres://postgres@localhost:5432/db
  FEEDBACK_URL: https://forms.office.com/Pages/ResponsePage.aspx?id=yXfS-grGoU2187O4s0qC-Qjm3BfYzDVIhkQadsLBtTxUMk01Qlc1R0dKRUQ0WEpPUUFYVzdWRllXUCQlQCN0PWcu
  GROVER_NO_SANDBOX: true
  EDITOR: vi

# ey-recovery
production:
  <<: *defaults
  DOMAIN: child-development-training.education.gov.uk
  TRACKING_ID: GTM-NFZ88TP # Live data
  HOTJAR_SITE_ID: 3169682
  # jobs
  GOOGLE_CLOUD_BUCKET: eyfs-recovery-production
  # DASHBOARD_UPDATE: false

# ey-recovery-staging
staging:
  <<: *defaults
  DOMAIN: ey-recovery-staging.london.cloudapps.digital
  TRACKING_ID: GTM-W6W95FD # Test data
  # cms
  CONTENTFUL_ENVIRONMENT: staging
  CONTENTFUL_PREVIEW: true
  # jobs
  GOOGLE_CLOUD_BUCKET: eyfs-data-dashboard-staging
  DASHBOARD_UPDATE: false

# ey-recovery-dev
development:
  <<: *defaults
  DOMAIN: ey-recovery-dev.london.cloudapps.digital
  # cms
  CONTENTFUL_ENVIRONMENT: test
  CONTENTFUL_PREVIEW: true
  # jobs
  GOOGLE_CLOUD_BUCKET: eyfs-data-dashboard-development
  DASHBOARD_UPDATE: false

# ey-recovery-content
content:
  <<: *defaults
  # jobs
  DASHBOARD_UPDATE: false
  # DASHBOARD_UPDATE_INTERVAL: '*/5 * * * *' # every 5 mins (default: daily at noon)
  # cms
  CONTENTFUL_ENVIRONMENT: training
  #
  # @see .github/workflows/content.yml
  # DOMAIN: xxx.london.cloudapps.digital
