---
# ------------------------------------------------------------------------------
# Terraform workspaces align to Cloud Foundry spaces
defaults: &defaults
  RAILS_SERVE_STATIC_FILES: true
  RAILS_LOG_TO_STDOUT: true
  RAILS_MAX_THREADS: 5
  RAILS_ENV: production
  NODE_ENV: production
  DATABASE_URL: postgres://postgres@localhost:5432/db

  # "DOMAIN"             = "${var.web_app_name}.london.cloudapps.digital"
  # "GOVUK_APP_DOMAIN"   = "${var.web_app_name}.london.cloudapps.digital"
  # "GOVUK_WEBSITE_ROOT" = "${var.web_app_name}.london.cloudapps.digital"

# ey-recovery
production:
  <<: *defaults

# ey-recovery-staging
staging:
  <<: *defaults

# ey-recovery-content
content:
  <<: *defaults
  DEMO_USER_PASSWORD: pa$$w0rd
