---
# ------------------------------------------------------------------------------
# Terraform workspaces align to Cloud Foundry spaces
defaults: &defaults
  RAILS_SERVE_STATIC_FILES: true
  RAILS_LOG_TO_STDOUT: true
  RAILS_MAX_THREADS: 5
  RAILS_ENV: production
  NODE_ENV: production
  DATABASE_URL: postgres://postgres@localhost:5432/db
  FEEDBACK_URL: https://forms.office.com/Pages/ResponsePage.aspx?id=yXfS-grGoU2187O4s0qC-Qjm3BfYzDVIhkQadsLBtTxUMk01Qlc1R0dKRUQ0WEpPUUFYVzdWRllXUCQlQCN0PWcu
  GOVUK_APP_DOMAIN: london.cloudapps.digital

# ey-recovery
production:
  <<: *defaults
  DOMAIN: child-development-training.education.gov.uk
  GOVUK_WEBSITE_ROOT: child-development-training

# ey-recovery-staging
staging:
  <<: *defaults
  DOMAIN: ey-recovery-staging.london.cloudapps.digital
  GOVUK_WEBSITE_ROOT: ey-recovery-staging

# ey-recovery-content
content:
  <<: *defaults
  # TRAINING_MODULES: demo-modules
  TIMEOUT_MINUTES: 60
  # @see workflow
  # DOMAIN: xxx.london.cloudapps.digital
  # GOVUK_WEBSITE_ROOT: xxx
