---
# ------------------------------------------------------------------------------
#
defaults: &defaults
  RAILS_SERVE_STATIC_FILES: true
  RAILS_LOG_TO_STDOUT: true
  RAILS_MAX_THREADS: 5
  # RAILS_MASTER_KEY:
  # APP_URL:
  # GOVUK_NOTIFY_API_KEY:
  # GOVUK_APP_DOMAIN:
  # GOVUK_WEBSITE_ROOT:
  # FEEDBACK_URL:

review:
  <<: *defaults
  RAILS_ENV: production
  NODE_ENV: production
  DATABASE_URL: postgres://postgres@localhost:5432/review
  DEMO_USER_PASWORD: pa$$w0rd
