---
# ------------------------------------------------------------------------------
# Terraform workspaces align to Cloud Foundry spaces
defaults: &defaults
  RAILS_SERVE_STATIC_FILES: true
  RAILS_LOG_TO_STDOUT: true
  RAILS_MAX_THREADS: 5
  RAILS_ENV: production
  NODE_ENV: production
  DATABASE_URL: postgres://postgres@localhost:5432/db
  FEEDBACK_URL: replace-me
  GOVUK_APP_DOMAIN: london.cloudapps.digital

# ey-recovery
production:
  <<: *defaults
  DOMAIN: ey-recovery.london.cloudapps.digital
  GOVUK_WEBSITE_ROOT: ey-recovery

# ey-recovery-staging
staging:
  <<: *defaults
  DOMAIN: ey-recovery-staging.london.cloudapps.digital
  GOVUK_WEBSITE_ROOT: ey-recovery-staging
  TRAINING_MODULES: demo-modules

# ey-recovery-content
content:
  <<: *defaults
  TRAINING_MODULES: demo-modules
  TIMEOUT_MINUTES: 60
  # @see workflow
  # DOMAIN: xxx.london.cloudapps.digital
  # GOVUK_WEBSITE_ROOT: xxx
