require 'capybara'
require 'capybara/rspec'
require 'selenium-webdriver'
require 'site_prism'
require 'site_prism/all_there'
require 'faker'
require 'active_support/core_ext/string/inflections'

Capybara.server_host = 'app'
Faker::Config.locale = 'en-GB'
