@startuml
hide stereotype

<style>
  .g {
    BackgroundColor LightSlateGray
    FontStyle italic
  }
}
</style>


legend
|<back:LightSlateGrey>Model</back>|
endlegend


rectangle "Early Years Recovery Application" {
  rectangle models <<g>> {
    class TrainingModule
    class ModuleItem
  }

  rectangle services {
    class CourseOverview
    class ModuleOverview
  }
}


' package "Some Group" {
'    HTTP - [First Component]
'   [Another Component]
' }

' node "Other Groups" {
'   FTP - [Second Component]
'   [First Component] --> FTP
' }

' cloud {
'   [Example 1]
' }


' database "MySql" {
'   folder "This is my folder" {
'     [Folder 3]
'   }
'   frame "Foo" {
'     [Frame 4]
'   }
' }


' [Another Component] --> [Example 1]
' [Example 1] --> [Folder 3]
' [Folder 3] --> [Frame 4]

@enduml
