@startuml
!theme sketchy-outline
hide stereotype

<style>
  .app {
    BackgroundColor LightBlue
  }
  .process {
    BackgroundColor LightGreen
    FontColor Black
  }
  .db {
    BackgroundColor DarkSlateGray
    FontColor White
  }
  .cache {
    BackgroundColor Yellow
  }
  .service {
    BackgroundColor LightSlateGray
    FontStyle italic
  }
}
</style>


legend top left
|<back:LightBlue>Container|
|<back:LightGreen>Process|
|<back:DarkSlateGray><color:White>Database|
|<back:Yellow>Cache|
|<back:LightSlateGrey>Third-party|
endlegend



rectangle "Early Years Child Development Training" {
  rectangle "Container" as db <<app>> {
    database "Database" as data <<db>>
  }

  rectangle "Container" as app <<app>> {
    node "Application" as web <<process>>
    database "Memory" as app_cache <<cache>>
  }

  rectangle "Container" as worker <<app>> {
    node "Worker" as jobs <<process>>
    database "Memory" as worker_cache <<cache>>
  }

  rectangle "Sentry" as alert <<service>>

  rectangle "Google Cloud Bucket" as dashboard <<service>>

  rectangle "Gov.uk Notify" as email <<service>>

  rectangle "Contentful CMS" as content <<service>>

  rectangle "Gov.uk One Login" as auth <<service>>
}


note right of db: Postgres 15.4 (alpine)
note left of app: Ruby 3.4.5 (alpine)
note bottom of web: Rails v7.1.3
note right of worker: Ruby 3.4.5 (alpine)
note bottom of jobs: Que v2.3.0

web <-u-> data
jobs <-u-> data

app <-- content: Preview/Delivery
app --> auth: OIDC
app --> alert

worker <-- content: Preview/Delivery
worker --> alert
worker <--> email
worker --> dashboard

@enduml
