@startuml
<style>
  .app {
    BackgroundColor LightBlue
  }
  .platform {
    BackgroundColor DarkSlateGray
    FontColor White
  }
  .subscription {
    BackgroundColor Yellow
  }
  .resource {
    BackgroundColor LightGreen
  }
  .service {
    BackgroundColor LightSlateGray
    FontStyle italic
  }
}
</style>


legend top left
|<back:DarkSlateGray><color:White>Platform|
|<back:Yellow>Subscription|
|<back:LightGreen>Resource Group|
|<back:LightBlue>Application|
endlegend


rectangle "Early Years Child Development Training" {

  rectangle "Github" as github <<service>>

  rectangle "Deployment" as deployment <<app>> {
    database "Database" as db
    rectangle "Container" as jobs
    rectangle "AppService" as web
  }

  rectangle "Azure" as azure <<platform>> {
    rectangle "s187-eyrecovery-production" as prod-sub <<subscription>> {
      rectangle "s187p01-eyrecovery-rg" as prod-rg <<resource>> {
        artifact "child-development-training.education.gov.uk" as prod <<app>>
        artifact "eyrecovery-prod-green.azurewebsites.net" as prod_green <<app>>
      }
    }

    rectangle "s187-eyrecovery-test" as test-sub <<subscription>> {
      rectangle "s187t01-eyrecovery-rg" as test-rg <<resource>> {
        artifact "staging.child-development-training.education.gov.uk" as test <<app>>
      }
    }

    rectangle "s187-eyrecovery-development" as dev-sub <<subscription>> {
      rectangle "s187d01-eyrecovery-rg" as dev-rg <<resource>> {
        artifact "eyrecovery-dev.azurewebsites.net" as dev <<app>>

        artifact "eyrecovery-review-pr-123.azurewebsites.net" as pr123 <<app>>
        artifact "eyrecovery-review-pr-124.azurewebsites.net" as pr124 <<app>>
        artifact "eyrecovery-review-pr-125.azurewebsites.net" as pr125 <<app>>
      }
    }
  }
}


note bottom of dev: main
note bottom of pr123: ER-456-new-feature
note bottom of test: rc0.2.10
note bottom of prod_green: pre-release
note bottom of prod: v1.0.0

web <--> db
jobs <--> db

github --> pr123: Active Branch (feature)
github --> dev: Development Branch (integration)
github --> test: Staging Release (candidate)
github --> prod: Production Release (public)

@enduml
