#
# 1. PASS ALPHA
# 2. FAIL BRAVO
# 3. PASS BRAVO
# 4. PARTIAL CHARLIE
#
---
#
#
#
#
# Prepare to start Alpha
#
- :path: /my-modules
  :text: My modules
  :inputs:
    - - :click_on
      - 'Module 1: First Training Module'
- :path: /modules/alpha
  :text: 'Module 1: First Training Module'
  :inputs:
    - - :click_on
      - Start module
#
#
#
#
# Alpha Pass
#
- :path: /modules/alpha/content-pages/what-to-expect
  :text: What to expect during the training
  :inputs:
    - - :click_on
      - Next
- :path: /modules/alpha/content-pages/1-1
  :text: The first submodule
  :inputs:
    - - :click_on
      - Start section
- :path: /modules/alpha/content-pages/1-1-1
  :text: 1-1-1
  :inputs:
    - - :click_on
      - Next
- :path: /modules/alpha/content-pages/1-1-2
  :text: 1-1-2
  :inputs:
    - - :click_on
      - Next
- :path: /modules/alpha/content-pages/1-1-3
  :text: 1-1-3
  :inputs:
    - - :click_on
      - Next
- :path: /modules/alpha/content-pages/1-1-3-1
  :text: 1-1-3-1
  :inputs:
    - - :click_on
      - Save and continue
- :path: /modules/alpha/content-pages/1-1-4
  :text: 1-1-4
  :inputs:
    - - :click_on
      - Next
- :path: /modules/alpha/questionnaires/1-1-4-1
  :text: Question One - Select from following
  :inputs:
    - - :choose
      - user-answer-answers-1-field
    - - :click_on
      - Next
    - - :click_on
      - Next
- :path: /modules/alpha/content-pages/1-2
  :text: The second submodule
  :inputs:
    - - :click_on
      - Start section
- :path: /modules/alpha/content-pages/1-2-1
  :text: 1-2-1
  :inputs:
    - - :click_on
      - Next
- :path: /modules/alpha/questionnaires/1-2-1-1
  :text: Question Two - Select from following
  :inputs:
    - - :check
      - user-answer-answers-1-field
    - - :check
      - user-answer-answers-3-field
    - - :click_on
      - Next
    - - :click_on
      - Next
- :path: /modules/alpha/content-pages/1-2-1-2
  :text: 1-2-1-2
  :inputs:
    - - :click_on
      - Next
- :path: /modules/alpha/questionnaires/1-2-1-3
  :text: Question Three - Select from following
  :inputs:
    - - :check
      - user-answer-answers-1-field
    - - :check
      - user-answer-answers-3-field
    - - :click_on
      - Next
    - - :click_on
      - Next
- :path: /modules/alpha/content-pages/1-3
  :text: Summary and next steps
  :inputs:
    - - :click_on
      - Start section
- :path: /modules/alpha/content-pages/1-3-1
  :text: Recap
  :inputs:
    - - :click_on
      - Next
- :path: /modules/alpha/content-pages/1-3-2
  :text: End of module test
  :inputs:
    - - :click_on
      - Start test
- :path: /modules/alpha/questionnaires/1-3-2-1
  :text: Question One - Select from following
  :inputs:
    - - :check
      - user-answer-answers-1-field
    - - :check
      - user-answer-answers-3-field
    - - :click_on
      - Save and continue
- :path: /modules/alpha/questionnaires/1-3-2-2
  :text: Question Two - Select from following
  :inputs:
    - - :check
      - user-answer-answers-2-field
    - - :check
      - user-answer-answers-3-field
    - - :click_on
      - Save and continue
- :path: /modules/alpha/questionnaires/1-3-2-3
  :text: Question Three - Select from following
  :inputs:
    - - :check
      - user-answer-answers-3-field
    - - :check
      - user-answer-answers-4-field
    - - :click_on
      - Save and continue
- :path: /modules/alpha/questionnaires/1-3-2-4
  :text: Question Four - Select from following
  :inputs:
    - - :choose
      - user-answer-answers-3-field
    - - :click_on
      - Save and continue
- :path: /modules/alpha/questionnaires/1-3-2-5
  :text: Question Five - Select from following
  :inputs:
    - - :choose
      - user-answer-answers-3-field
    - - :click_on
      - Save and continue
- :path: /modules/alpha/questionnaires/1-3-2-6
  :text: Question Six - Select from following
  :inputs:
    - - :choose
      - user-answer-answers-3-field
    - - :click_on
      - Save and continue
- :path: /modules/alpha/questionnaires/1-3-2-7
  :text: Question Seven - Select from following
  :inputs:
    - - :choose
      - user-answer-answers-3-field
    - - :click_on
      - Save and continue
- :path: /modules/alpha/questionnaires/1-3-2-8
  :text: Question Eight - Select from following
  :inputs:
    - - :choose
      - user-answer-answers-3-field
    - - :click_on
      - Save and continue
- :path: /modules/alpha/questionnaires/1-3-2-9
  :text: Question Nine - Select from following
  :inputs:
    - - :choose
      - user-answer-answers-3-field
    - - :click_on
      - Save and continue
- :path: /modules/alpha/questionnaires/1-3-2-10
  :text: Question Ten - Select from following
  :inputs:
    - - :choose
      - user-answer-answers-3-field
    - - :click_on
      - Finish test
- :path: /modules/alpha/assessment-result/1-3-2-11
  :text: Assessment results
  :inputs:
    - - :click_on
      - Next
- :path: /modules/alpha/content-pages/1-3-3
  :text: Reflect on your learning
  :inputs:
    - - :click_on
      - Next
- :path: /modules/alpha/questionnaires/1-3-3-1
  :text: Question One - Select from 1 to 5
  :inputs:
    - - :choose
      - user-answer-answers-5-field
    - - :click_on
      - Next
- :path: /modules/alpha/questionnaires/1-3-3-2
  :text: Question Two - Select from 1 to 5
  :inputs:
    - - :choose
      - user-answer-answers-5-field
    - - :click_on
      - Next
- :path: /modules/alpha/questionnaires/1-3-3-3
  :text: Question Three - Select from 1 to 5
  :inputs:
    - - :choose
      - user-answer-answers-5-field
    - - :click_on
      - Next
- :path: /modules/alpha/questionnaires/1-3-3-4
  :text: Question Four - Select from 1 to 5
  :inputs:
    - - :choose
      - user-answer-answers-5-field
    - - :click_on
      - Next
- :path: /modules/alpha/content-pages/1-3-3-5
  :text: Thank you
  :inputs:
    - - :click_on
      - Finish
- :path: /modules/alpha/content-pages/1-3-4
  :text: Congratulations!
  :inputs:
    - - :click_on
      - My modules
#
#
#
#
# Prepare to start Bravo
#
- :path: /my-modules
  :text: My modules
  :inputs:
    - - :click_on
      - 'Module 2: Second Training Module'
- :path: /modules/bravo
  :text: 'Module 2: Second Training Module'
  :inputs:
    - - :click_on
      - Start module
#
#
#
#
# Bravo Pass
#
# - :path: /modules/bravo/content-pages/what-to-expect
#   :text: What to expect during the training
#   :inputs:
#     - - :click_on
#       - Next
# - :path: /modules/bravo/content-pages/1-1
#   :text: first sub intro
#   :inputs:
#     - - :click_on
#       - Start section
# - :path: /modules/bravo/content-pages/1-1-1
#   :text: page 1 of sub 1 (topic 1)
#   :inputs:
#     - - :click_on
#       - Next
# - :path: /modules/bravo/content-pages/1-1-2
#   :text: page 2 of sub 1 (topic 2)
#   :inputs:
#     - - :click_on
#       - Next
# - :path: /modules/bravo/content-pages/1-1-2-1
#   :text: page 3 of sub 1 (topic 2 page 2)
#   :inputs:
#     - - :click_on
#       - Next



- :path: /modules/bravo/content-pages/what-to-expect
  :text: What to expect during the training
  :inputs:
  - - :click_on
    - Next
- :path: /modules/bravo/content-pages/1-1
  :text: sub_module_intro
  :inputs:
  - - :click_on
    - Start section
- :path: /modules/bravo/content-pages/1-1-1
  :text: text_page
  :inputs:
  - - :click_on
    - Next
- :path: /modules/bravo/content-pages/1-1-2
  :text: video_page
  :inputs:
  - - :click_on
    - Next
- :path: /modules/bravo/content-pages/1-1-2-1
  :text: text_page
  :inputs:
  - - :click_on
    - Next
- :path: /modules/bravo/content-pages/1-2
  :text: sub_module_intro
  :inputs:
  - - :click_on
    - Start section
- :path: /modules/bravo/content-pages/1-2-1
  :text: text_page
  :inputs:
  - - :click_on
    - Next
- :path: /modules/bravo/content-pages/1-2-1-1
  :text: text_page
  :inputs:
  - - :click_on
    - Next
- :path: /modules/bravo/content-pages/1-2-1-2
  :text: video_page
  :inputs:
  - - :click_on
    - Next
- :path: /modules/bravo/questionnaires/1-2-1-3
  :text: Binary choice
  :inputs:
  - - :choose
    - user-answer-answers-2-field
  - - :click_on
    - Next
  - - :click_on
    - Next
- :path: /modules/bravo/content-pages/1-3
  :text: Summary and next steps
  :inputs:
  - - :click_on
    - Start section
- :path: /modules/bravo/content-pages/1-3-1
  :text: Recap
  :inputs:
  - - :click_on
    - Next
- :path: /modules/bravo/content-pages/1-3-2
  :text: End of module test
  :inputs:
  - - :click_on
    - Start test
- :path: /modules/bravo/questionnaires/1-3-2-1
  :text: Question One - Select from following
  :inputs:
  - - :check
    - user-answer-answers-2-field
  - - :check
    - user-answer-answers-4-field
  - - :click_on
    - Save and continue
- :path: /modules/bravo/questionnaires/1-3-2-2
  :text: Question Two - Select from following
  :inputs:
  - - :check
    - user-answer-answers-1-field
  - - :check
    - user-answer-answers-4-field
  - - :click_on
    - Save and continue
- :path: /modules/bravo/questionnaires/1-3-2-3
  :text: Question Three - Select from following
  :inputs:
  - - :check
    - user-answer-answers-1-field
  - - :check
    - user-answer-answers-4-field
  - - :click_on
    - Save and continue
- :path: /modules/bravo/questionnaires/1-3-2-4
  :text: Question Four - Select from following
  :inputs:
  - - :check
    - user-answer-answers-1-field
  - - :check
    - user-answer-answers-4-field
  - - :click_on
    - Save and continue
- :path: /modules/bravo/questionnaires/1-3-2-5
  :text: Question Five - Select from following
  :inputs:
  - - :check
    - user-answer-answers-1-field
  - - :check
    - user-answer-answers-4-field
  - - :click_on
    - Save and continue
- :path: /modules/bravo/questionnaires/1-3-2-6
  :text: Question Six - Select from following
  :inputs:
  - - :check
    - user-answer-answers-1-field
  - - :check
    - user-answer-answers-4-field
  - - :click_on
    - Save and continue
- :path: /modules/bravo/questionnaires/1-3-2-7
  :text: Question Seven - Select from following
  :inputs:
  - - :check
    - user-answer-answers-1-field
  - - :check
    - user-answer-answers-4-field
  - - :click_on
    - Save and continue
- :path: /modules/bravo/questionnaires/1-3-2-8
  :text: Question Eight - Select from following
  :inputs:
  - - :check
    - user-answer-answers-1-field
  - - :check
    - user-answer-answers-4-field
  - - :click_on
    - Save and continue
- :path: /modules/bravo/questionnaires/1-3-2-9
  :text: Question Nine - Select from following
  :inputs:
  - - :check
    - user-answer-answers-1-field
  - - :check
    - user-answer-answers-4-field
  - - :click_on
    - Save and continue
- :path: /modules/bravo/questionnaires/1-3-2-10
  :text: Question Ten - Select from following
  :inputs:
  - - :check
    - user-answer-answers-1-field
  - - :check
    - user-answer-answers-4-field
  - - :click_on
    - Finish test
