name: 'App Deploy [Azure - REVIEW TEARDOWN]'

on:
  pull_request:
    types:
      - closed

# Permissions for OIDC authentication
permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  DOCKER_IMAGE: ghcr.io/dfe-digital/early-years-foundation-recovery
  PR_NUMBER: pr-${{ github.event.number }}

jobs:
  teardown:
    runs-on: ubuntu-latest
    environment: development

    steps:
      # Login to Azure using OIDC
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Destroy Web Application
      - name: Deploy to Azure App Services
        uses: azure/CLI@v1
        with:
          azcliversion: 2.50.0
          inlineScript: |
            az webapp deployment slot delete --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --name ${{ vars.REVIEWAPP_NAME }} \
              --slot ${{ env.PR_NUMBER }}