---
# ------------------------------------------------------------------------------
# https://github.com/DFE-Digital/early-years-foundation-recovery/actions/workflows/ci-docker-compose.yml
#
name: Continuous Integration using Docker Compose
on:
  workflow_dispatch:

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  test:
    name: Rspec & Rubocop
    runs-on: ubuntu-latest
    environment: test

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3
      -
        name: Build application Docker image
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml --project-name recovery build
      -
        name: Run Rspec suite
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml --project-name recovery run --rm app rspec
      -
        name: Run Rubocop linting
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml --project-name recovery run --rm app rubocop
