---
name: Continuous Integration using Docker Compose
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  test:
    name: Rspec & Rubocop
    runs-on: ubuntu-latest
    environment: test

    steps:
      -
        name: Check out code
        uses: actions/checkout@v2
      -
        name: Build application Docker image
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml --project-name recovery build
      -
        name: Run Rspec suite
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml --project-name recovery run --rm app rspec
      -
        name: Run Rubocop linting
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml --project-name recovery run --rm app rubocop
