---
# ------------------------------------------------------------------------------
#
name: Continuous Integration
on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - .docker*
      - .env.example
      - .gitignore
      - .pa11yci
      - .tool-versions
      - .yardopts
      - bin/*
      - docker-compose.*
      - Dockerfile
      - terraform

env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  DATABASE_URL: postgres://postgres:password@localhost:5432/test
  DOMAIN: recovery.app
  TRAINING_MODULES: demo-modules
  TIMEOUT_MINUTES: 3
  TIMEOUT_WARNING_MINUTES: 1
  TIMEOUT_MODAL_VISIBLE: 1
  BOT_TOKEN: bot_token
  GOOGLE_CLOUD_STORAGE: '{"type": "gcs","project_id": "test","private_key_id": "ndqiqwfdibewifbiewfb","private_key": "-----BEGIN RSA PRIVATE KEY-----\nMIICXwIBAAKBgQDdX5eABMRfIhYDwIAOcIOu8C0KLLGIHoo++Pvl4h3sYYdi1qHX\nFWs07dYLyv8xuVWvkQEgTXFOp52qDMcVgvpTCH1ziuybbbjkLcn84y5nK8+g2Azr\nPbVyaK6IGFT35uT+M41dEr9luYSAVTG2zmNYlZqMZFr/GOhsO0xTgUdEiwIDAQAB\nAoGBAJuE4XENaEuRLbgbD5uVTd2jW3DvbxU6p1KQJp8cWHtNFQjJ0k7A/FzlzV7h\nkKCFHH5Ht2vTHAvu02O4sFAbgPFv0yJOClKnorsj3fpCjCXhh6EsRC14ypVygUYe\nFKuxeSLEDJn49CPUMIbrJOj2ggcHnOE8+P2wL4Ag4iafvv4xAkEA8tnN6KfwsnpD\n9sH5XqPqwMFRYyYH0A9a5McAVxIV4lZfLkhsIlu9owUmW9rDUzVwsTzWqplJwqXu\nM5jdmEzI2QJBAOlcFfHSKojFoVcitqIRudJrFy6LxK4kV4H/sRUWxN6/j68xxO6Z\nJzAlHQYzlOjwXg+MLBfhJ0yRMMSjHFAF+gMCQQCnCfU9sDY5LSwOUIHL/Qd9qfrn\nLcN18vncHp03RrNSyYISfbITN/MKbIJj7+cmFr36yxQEqAc6IZPkXaMeHMKRAkEA\nzSMpG1IAGAl7Qgj++UuRyVpgn4c4V0kVL+8gsQQ5/gHxgjXDA2fYnicR86Cmd3rN\nhOdY34kKrfE4KLOmMOaAFwJBANai4GX7WHuFCqBeQbXZGiWVJQdz2mad0uZcZv81\n+tPQdHXjK1FTIg9SPY3Bmn7o78FnZ0c5fT+tB4GNnTyg+uo=\n-----END RSA PRIVATE KEY-----","client_email": "test@test.iam.gserviceaccount.com","client_id": "241251251251251252","auth_uri": "https://accounts.google.com/o/oauth2/auth","token_uri": "https://oauth2.googleapis.com/token","auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata"}'

jobs:
  test:
    name: Test and lint code
    runs-on: ubuntu-latest
    environment: test

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3
      -
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      -
        name: Install Rubygems
        run: bundle install --jobs 20 --retry 3
      -
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      -
        name: Compile assets
        run: bundle exec rails assets:precompile
      -
        name: Prepare test database
        run: bin/rails db:prepare
        env:
          NOTIFY_API_KEY: foo
      -
        name: Run test suite
        run: bundle exec rspec
      -
        name: Run rubocop
        run: bundle exec rubocop
