---
# ------------------------------------------------------------------------------
#
name: Continuous Integration
on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - .docker*
      - .env.example
      - .gitignore
      - .pa11yci
      - .tool-versions
      - .yardopts
      - bin/*
      - docker-compose.*
      - Dockerfile
      - terraform

jobs:
  test:
    name: Test and lint code
    runs-on: ubuntu-latest
    environment: test
    env:
      RAILS_ENV: test
      # https://github.com/DFE-Digital/early-years-foundation-recovery/settings/secrets/dependabot
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DATABASE_URL: postgres://postgres:password@localhost:5432/test
      DOMAIN: recovery.app
      TRAINING_MODULES: demo-modules
      BOT_TOKEN: bot_token

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3
      -
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true
      -
        name: Install Rubygems
        run: bundle install --jobs 20 --retry 3
      -
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      -
        name: Prepare test database
        run: bin/rails db:prepare
      -
        name: Report schema version
        run: bin/rails db:version
      -
        name: Compile assets
        run: bin/rails assets:precompile
      -
        name: Run test suite
        run: bundle exec rspec
      -
        name: Run rubocop
        run: bundle exec rubocop
