---
# ------------------------------------------------------------------------------
#
name: Continuous Integration
on:
  merge_group:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - .docker*
      - .env.example
      - .gitignore
      - .pa11yci
      - .tool-versions
      - .yardopts
      - bin/*
      - docker-compose.*
      - Dockerfile
      - terraform
      - terraform-azure

jobs:
  test:
    name: Test and lint code
    runs-on: ubuntu-latest
    environment: test
    env:
      RAILS_ENV: test
      # https://github.com/DFE-Digital/early-years-foundation-recovery/settings/secrets/dependabot
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DATABASE_URL: postgres://postgres:password@localhost:5432/test
      DOMAIN: recovery.app
      BOT_TOKEN: bot_token

    services:
      postgres:
        image: postgres:15.4-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v4
      -
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      -
        name: Install Rubygems
        run: bundle install --jobs 20 --retry 3
      -
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      -
        name: Prepare test database
        run: bundle exec rails db:create db:migrate
      -
        name: Report schema version
        run: bundle exec rails db:version
      -
        name: Compile assets
        run: bundle exec rails assets:precompile
      -
        name: Run test suite
        run: bundle exec rspec
      -
        name: Run rubocop
        run: bundle exec rubocop
      # -
      #   name: Run test suite
      #   run: bundle exec rspec
      #   env:
      #     DISABLE_USER_ANSWER: true
