---
name: Rspec within Docker
on:
  - push

jobs:
  test:
    name: Run the test suite inside Docker
    runs-on: ubuntu-latest
    environment: test
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
      -
        name: Check out code
        uses: actions/checkout@v2
      -
        name: Build application Docker image
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml --project-name recovery build
      -
        name: Run Rspec suite
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml --project-name recovery run --rm app rspec -f doc

