---
# https://github.com/docker/build-push-action
#
name: Docker
on:
  - push
  - pull_request

jobs:
  test:
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/dfe-digital/early-years-foundation-recovery

    steps:
      # ------------------------------------------------------------------------
      - name: Checkout Code
        uses: actions/checkout@v2

      # ------------------------------------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # ------------------------------------------------------------------------
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      # ------------------------------------------------------------------------
      #   ghcr.io/dfe-digital/early-years-foundation-recovery-production:latest
      #
      - name: Build and push Docker production image
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: |
            ${{ env.DOCKER_IMAGE }}-production:latest
          push: true
          tags: ${{ env.DOCKER_IMAGE }}-production:latest
          target: app
