---
# ------------------------------------------------------------------------------
#
name: Notify callback simulator
on:
  workflow_dispatch:
    inputs:
      deployment:
        description: development, staging, production
        type: string
        default: staging
      email:
        description: User email address
        type: string

jobs:
  test:
    name: webhook
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment }}
    steps:
      - name: Mock test message delivery
        run: |
          curl \
            --no-progress-meter \
            --request POST \
            --header 'Authorization: Bearer token ${{ secrets.BOT_TOKEN }}' \
            --header 'Content-type: application/json' \
            --data '{"to":"${{ inputs.email }}","template_id":"7c5fa953-4208-4bc4-919a-4ede23db65c1","status":"delivered","notification_type":"email"}' \
            'https://${{ vars.WEBAPP_CONFIG_DOMAIN }}/notify'
