---
# ------------------------------------------------------------------------------
# Run workflow:
#   https://github.com/DFE-Digital/early-years-foundation-recovery/actions/workflows/production.yml
#
# Build image:
#   ghcr.io/dfe-digital/early-years-foundation-recovery:v0.0.x
#
# Deploy to:
#   https://child-development-training.education.gov.uk
#
name: Deploy Production App
on:
  workflow_dispatch:
    inputs:
      version:
        description: Create release version ("vx.x.x")
        type: string
        required: true
      ref:
        description: Release candidate to deploy ("rcx.x.x")
        type: string
        required: true
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      WORKSPACE: production
      REGISTRY: ghcr.io/dfe-digital/early-years-foundation-recovery
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref || github.ref_name }}
      -
        name: Tag version
        if:  ${{ inputs.version }}
        run: |
          git tag --force ${{ inputs.version }}
          git push --force origin refs/tags/${{ inputs.version }}
          echo "HEAD=$(git rev-parse ${{ inputs.version }})" >> $GITHUB_ENV
      -
        name: Pin Terraform version
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.1.7
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          target: app
          context: .
          push: true
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            SHA=${{ github.sha }}
          cache-from: |
            ${{ env.REGISTRY }}:${{ github.sha }}
            ${{ env.REGISTRY }}:${{ inputs.ref || github.ref_name }}
          tags: |
            ${{ env.REGISTRY }}:${{ github.sha }}
            ${{ env.REGISTRY }}:${{ inputs.ref || github.ref_name }}
      -
        name: Production Release
        env:
          # init
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # plan/apply
          TF_VAR_paas_cf_user: ${{ secrets.CLOUD_FOUNDRY_USERNAME }}
          TF_VAR_paas_cf_password: ${{ secrets.CLOUD_FOUNDRY_PASSWORD }}
          TF_VAR_paas_app_docker_image: ${{ env.REGISTRY }}:${{ inputs.ref || github.ref_name }}
          TF_VAR_paas_app_env_secrets: ${{ toJson(secrets) }}
          TF_VAR_paas_app_envs: ${{ toJson(env) }}
        run: |
          cd terraform/app
          terraform init \
            -reconfigure \
            -input=false \
            -backend-config="bucket=${{ secrets.AWS_BUCKET }}" \
            -backend-config="key=${{ env.WORKSPACE }}/terraform.tfstate"
          terraform plan \
            -var-file ../workspace-variables/${{ env.WORKSPACE }}.tfvars
          terraform apply \
            -input=false \
            -auto-approve \
            -var-file ../workspace-variables/${{ env.WORKSPACE }}.tfvars
      -
        name: Install Cloud Foundry CLI
        uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          CF_USERNAME: ${{ secrets.CLOUD_FOUNDRY_USERNAME }}
          CF_PASSWORD: ${{ secrets.CLOUD_FOUNDRY_PASSWORD }}
          CF_SPACE_NAME: ey-recovery
      -
        name: Map production DNS route
        run: |
          cf map-route ey-recovery education.gov.uk --hostname child-development-training
