---
# ------------------------------------------------------------------------------
#
# Run the end-to-end test suit against applications running in production
#
name: QA Framework using Docker Compose
on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

  workflow_run:
    workflows:
      - Deploy Content App
    branches:
      - main
    types:
      - completed

env:
  RAILS_ENV: production
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
  

jobs:
  test:
    name: Run Rspec
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3
      -
        name: Build Docker images
        run: docker-compose -f docker-compose.yml -f docker-compose.qa.yml --project-name recovery build
      -
        name: Build self-signed certificates
        run: |
          openssl req \
            -nodes -x509 -sha256 \
            -newkey rsa:2048 \
            -keyout localhost.key \
            -out localhost.crt \
            -subj "/C=GB/ST=London/L=London/O=DfE/OU=EYFS/CN=example.com"
      -
        name: Firefox against docker app
        run: docker-compose -f docker-compose.yml -f docker-compose.qa.yml --project-name recovery run qa
        env:
          BASE_URL: https://app:3000
          BROWSER: standalone_firefox
      # -
      #   name: Chrome against docker app
      #   run: docker-compose -f docker-compose.yml -f docker-compose.qa.yml --project-name recovery run qa
      #   env:
      #     BASE_URL: https://app:3000
      #     BROWSER: standalone_chrome
      # -
      #   name: Firefox against deployed app
      #   run: docker-compose -f docker-compose.yml -f docker-compose.qa.yml --project-name recovery run qa
      #   env:
      #     BASE_URL: https://ey-recovery-pr-${{ github.event.number }}.london.cloudapps.digital
      #     BROWSER: standalone_firefox
      # -
      #   name: Chrome against deployed app
      #   run: docker-compose -f docker-compose.yml -f docker-compose.qa.yml --project-name recovery run qa
      #   env:
      #     BASE_URL: https://ey-recovery-pr-${{ github.event.number }}.london.cloudapps.digital
      #     BROWSER: standalone_chrome
