---
name: QA Framework
on:
  workflow_dispatch:

  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - synchronize

  # workflow_run:
  #   workflows:
  #     - Deploy Content App
  #   branches:
  #     - main
  #   types:
  #     - completed

env:
  BASE_URL: https://ey-recovery-pr-${{ github.event.number }}.london.cloudapps.digital
  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

jobs:
  test:
    name: Standalone UI tests
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4441:4444

      firefox:
        image: selenium/standalone-firefox:latest
        ports:
          - 4442:4444

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3
      -
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
      -
        name: Set up ruby gem cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      -
        name: Install Rubygems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 20 --retry 3
      -
        name: Run test suite against firefox
        env:
          BROWSER: standalone_firefox
        run: bin/rspec --default-path ui
      # -
      #   name: Run test suite against chrome
      #   env:
      #     BROWSER: standalone_chrome
      #   run: bin/rspec --default-path ui
