---
# ------------------------------------------------------------------------------
# TODO: Run once the review app is deployed
#
name: QA Framework
on:
  workflow_dispatch:
    inputs:
      workspace:
        description: PR number to test against (pr-xxx)
        type: string
        required: true

  pull_request:

  # workflow_run:
  #   workflows:
  #     - Deploy Content App
  #   types:
  #     - completed

env:
  BASE_URL: https://ey-recovery-pr-${{ inputs.ref || github.event.number }}.london.cloudapps.digital
  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

jobs:
  test:
    name: QA checks
    # trigger by deployment
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # trigger by label
    if: contains(github.event.pull_request.labels.*.name, 'deployed')
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4441:4444
      firefox:
        image: selenium/standalone-firefox:latest
        ports:
          - 4442:4444

    steps:
      -
        name: Checkout deployed code
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.event.workflow_run.head_branch }}
      -
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true
      -
        name: Install Rubygems
        run: bundle install --jobs 20 --retry 3
      -
        name: Use Chrome
        env:
          BROWSER: standalone_chrome
        run: bin/rspec --default-path ui
      -
        name: Use Firefox
        env:
          BROWSER: standalone_firefox
        run: bin/rspec --default-path ui
