---
name: QA Framework
on:
  workflow_dispatch:

  workflow_run:
    workflows:
      - Deploy Content App
    branches:
      - main
    types:
      - completed

env:
  BASE_URL: https://ey-recovery-pr-${{ github.event.number }}.london.cloudapps.digital
  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

jobs:
  test:
    name: QA checks
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4441:4444

      firefox:
        image: selenium/standalone-firefox:latest
        ports:
          - 4442:4444

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3
      -
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      -
        name: Install Rubygems
        run: bundle install --jobs 20 --retry 3
      -
        name: Run test suite against chrome
        env:
          BROWSER: standalone_chrome
        run: bin/rspec --default-path ui
      -
        name: Run test suite against firefox
        env:
          BROWSER: standalone_firefox
        run: bin/rspec --default-path ui
