---
name: QA Framework
on:
  workflow_dispatch:
  #   inputs:
  #     workspace:
  #       description: Deployment workspace to test against (dev, pr-xxx)
  #       type: string
  #       default: dev

  pull_request:
    branches:
      - main
    types:
      - synchronize

  workflow_run:
    workflows:
      - Deploy Content App
    branches:
      - main
    types:
      - completed

env:
  # BASE_URL: https://ey-recovery-pr-${{ github.event.number }}.london.cloudapps.digital
  BASE_URL: https://ey-recovery-dev.london.cloudapps.digital
  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

jobs:
  test:
    name: QA checks
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
      firefox:
        image: selenium/standalone-firefox:latest
        ports:
          - 4444:4444

    steps:
      -
        name: Print URL
        run: echo $BASE_URL
      -
        name: Checkout Code
        uses: actions/checkout@v3
      -
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      -
        name: Install Rubygems
        run: bundle install --jobs 20 --retry 3
      -
        name: Use Chrome
        env:
          BROWSER: standalone_chrome
          DRIVER: chrome:4444
        run: bin/rspec --default-path ui
      -
        name: Use Firefox
        env:
          BROWSER: standalone_firefox
          DRIVER: firefox:4444
        run: bin/rspec --default-path ui
