---
# ------------------------------------------------------------------------------
#
# https://github.com/DFE-Digital/early-years-foundation-recovery/settings/secrets/actions
# https://docs.github.com/en/enterprise-server@3.4/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging
#
name: Deploy Review App
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      WORKSPACE: review
      DOCKER_IMAGE: ghcr.io/dfe-digital/early-years-foundation-recovery
      REVIEW_PR_NUMBER: ${{ env.WORKSPACE }}-pr-${{ github.event.number }}
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      -
        name: Pin Terraform version
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 1.1.7
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        # ghcr.io/dfe-digital/early-years-foundation-recovery:review-pr-123
        name: Build and push Docker production image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            SHA=${{ github.event.pull_request.head.sha }}
          cache-from: |
            ${{ env.DOCKER_IMAGE }}:${{ env.REVIEW_PR_NUMBER }}
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ env.REVIEW_PR_NUMBER }}
            ${{ env.DOCKER_IMAGE }}:${{ github.event.pull_request.head.sha }}
          target: app

      -
        name: Deploy Review App
        env:
          TF_VAR_paas_cf_user: ${{ secrets.CLOUD_FOUNDRY_USERNAME }}
          TF_VAR_paas_cf_password: ${{ secrets.CLOUD_FOUNDRY_PASSWORD }}
          TF_VAR_paas_app_docker_image: ${{ env.DOCKER_IMAGE }}:${{ github.event.pull_request.head.sha }}
        run: |
          cd terraform/app
          terraform init \
            -reconfigure \
            -input=false \
            -backend-config="bucket=${{ secrets.AWS_BUCKET }}" \
            -backend-config="key=${{ env.REVIEW_PR_NUMBER }}/terraform.tfstate"
          terraform plan \
            -var-file ../workspace-variables/${{ env.WORKSPACE }}.tfvars
          terraform apply \
            -input=false \
            -auto-approve \
            -var-file ../workspace-variables/${{ env.WORKSPACE }}.tfvars \
            -var='paas_app_hostname=${{ env.REVIEW_PR_NUMBER }}' \
            -var='paas_app_env_secrets={
              "AWS_ACCESS_KEY_ID": "${{ secrets.AWS_ACCESS_KEY_ID }}",
              "AWS_SECRET_ACCESS_KEY": "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
              "AWS_BUCKET": "${{ secrets.AWS_BUCKET }}",
              "RAILS_MASTER_KEY": "${{ secrets.RAILS_MASTER_KEY }}"
            }'

