# ------------------------------------------------------------------------------
name: Teardown Content App

on:
  workflow_dispatch:
  pull_request:
  #   types:
  #     - closed
  # remove before merging in
    branches:
      - main

jobs:
  teardown-content:
    if: contains(github.event.pull_request.labels.*.name, 'deployed')
    runs-on: ubuntu-latest
    environment: production
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      -
        name: Pin Terraform version
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.1.7
      -
        name: Install Cloud Foundry CLI
        uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          # default arg values
          # CF_CLI_VERSION: v7
          # CF_ORG_NAME: dfe
          # CF_API_URL:  https://api.london.cloud.service.gov.uk
          # INSTALL_CONDUIT: false
          CF_USERNAME: ${{ secrets.CLOUD_FOUNDRY_USERNAME }}
          CF_PASSWORD: ${{ secrets.CLOUD_FOUNDRY_PASSWORD }}
          CF_SPACE_NAME: ey-recovery-content
      -
        name: Drop branch database and delete application
        env:
          APP_NAME: ey-recovery-pr-${{ github.event.number }}
          DB_NAME: ey-recovery-db-review
          CMD: source .profile; cd $APP_HOME; DISABLE_DATABASE_ENVIRONMENT_CHECK=1 rails db:drop
        run: |
          cf ssh $APP_NAME -c "$CMD"
          cf stop $APP_NAME
          cf unbind-service $APP_NAME $DB_NAME
          cf delete $APP_NAME -r -f
